// You must export a type to be generated the schema
export * from './Activity'
export * from './AuthPayload'
export * from './Mutation'
export * from './Org'
export * from './Post'
export * from './Query'
export * from './User'
export * from './Group'
export * from './Profile'
export * from './Schedule'
export * from './Attendance'
