name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - id: deploy
      name: Deploy to dokku-us
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 'us-seattle-m1.nodes.vgm.me'
          app-name: 'ekklisia-graph'
